#!/bin/bash
# If you want to build strace2ds library, just run this script.
# If you want to build and install, run this script with 'install' argument. Ex: ./buildall install
function runcmd
{
    echo "CMD: $@"
    sleep 0.2
    $@
    ret=$?
    if test $ret -ne 0 ; then
	exit $ret
    fi
}

runcmd autoreconf -v -i
runcmd /bin/rm -fr BUILD
runcmd mkdir -p BUILD
if [ ! -e "./xml" ] || [ "./xml" -ot "./tables/snia_syscall_fields.table" ]
then
    runcmd ./generate-xml.sh ./tables/snia_syscall_fields.table
fi
runcmd cp -r ./xml BUILD
runcmd cd BUILD
runcmd ../configure --enable-shared --disable-static --prefix=$HOME/lib/strace2ds
runcmd make clean
# if all you're changing is C/C++ code, just "cd BUILD" and run next
# two commands.
runcmd make
if [ "$#" -eq 1 ] && [ "$1" = "install" ]
then
    runcmd make install
fi
