#!/bin/bash

function runcmd
{
    echo "CMD: $@"
    sleep 0.2
    $@
    ret=$?
    if test $ret -ne 0 ; then
	exit $ret
    fi
}

runcmd autoreconf -v -i
runcmd /bin/rm -fr BUILD
runcmd mkdir -p BUILD
runcmd cd BUILD
runcmd ../configure --enable-shared --disable-static --prefix=$HOME/strace2ds
runcmd make clean
runcmd make
runcmd make install
