Common(time_called);
read(descriptor,data_read,bytes_requested);
write(descriptor,data_written,bytes_requested);
close(descriptor);
open(given_pathname,flag_read_only,flag_write_only,flag_read_and_write,flag_append,flag_async,flag_create,flag_direct,flag_directory,flag_exclusive,flag_largefile,flag_no_access_time,flag_no_controlling_terminal,flag_no_follow,flag_no_blocking_mode,flag_no_delay,flag_synchronous,flag_truncate,flag_close_on_exec);